# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI
on:
  push:
    branches: [ feature/** ]

jobs:
  job1:
    name: Git IDs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Git Id and diff files
      run: |
        echo "This is the current commit" $GITHUB_SHA
        sha_pre=$(git log --pretty=format:"%H" --merges -n 1)
        echo "This is the previous commit" $sha_pre
        export sha_diff=$(git diff --pretty=format: --name-only $GITHUB_SHA $sha_pre)
        echo "$sha_diff" > ./NewDiff.txt
        cat -n ./NewDiff.txt

    - name: Upload Diff File
      uses: actions/upload-artifact@v2
      with:
        name: DifferenceFile
        path: ./NewDiff.txt
    - name: Download Diff File
      uses: actions/download-artifact@v2
      with:
        name: DifferenceFile
        path: ./DownloadedDiff.txt
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./
  job2:
    name: Download Artifact
    runs-on: ubuntu-latest
    steps:
    - name: Download Diff File
      uses: actions/download-artifact@v2
      with:
        name: DifferenceFile
        path: ./
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./
