# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI
env:
  Diff: ${{sha_diff}}
on:
  push:
    branches: [ feature/** ]

jobs:
  job1:
    name: Git IDs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Id and diff files
      run: |
        echo "This is the current commit" $GITHUB_SHA
        sha_pre=$(git log --pretty=format:"%H" --merges -n 1)
        echo "This is the previous commit" $sha_pre
        sha_diff=$(git diff --pretty=format: --name-only $GITHUB_SHA $sha_pre)
        echo $Diff
  job2:
    name: Run Ant commands
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -buildfile build.xml diffBuilderWithGitCommit
