name: Feature Branch Workflow

on:
  push:
    branches:
      - "feature/**"
    paths:
      - "force-app/**"

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  SF_ORG__SIT__AUTH_URL: ${{ secrets.SF_ORG__SIT__AUTH_URL }}

jobs:
  Validate_Against_SIT:
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0
    steps:
      - uses: actions/checkout@v1

      - name: Get Current Git Id
        run: |
          echo $GITHUB_SHA
          sha_pre=$(git rev-parse HEAD~1)
          echo $sha_pre
          sha_diff=$(git diff --pretty=format: --name-only $GITHUB_SHA $sha_pre)
          echo $sha_diff

      - name: Populate auth file with SFDX_URL secret
        shell: bash
        run: echo ${{ secrets.SF_ORG__SIT__AUTH_URL}} > ./SFDX_URL_STORE.txt

      - name: Authenticate against dev hub
        run : sfdx force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=DevHub --setdefaultdevhubusername

      - name: Run Validation against SIT
        run: sfdx force:source:deploy --sourcepath force-app/main/default --checkonly --testlevel NoTestRun --targetusername DevHub
