# This is a basic workflow to help you get started with Actions

name: Master Branch Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    # Only trigger a workflow when changes have been made to files in the below mentioned path.
    paths:
      - "force-app/**"

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  SF_ORG__UAT__AUTH_URL: ${{ secrets.SF_ORG__UAT__AUTH_URL }}
  SF_ORG__PROD__AUTH_URL: ${{ secrets.SF_ORG__PROD__AUTH_URL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_To_UAT:
    needs: SonarQube_Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run Deployment against UAT
        run: sfdx deploy:source --sourcepath force-app/main/default --testlevel NoTestRun --targetalias UAT

  Validate_Against_Production:
    needs: [SonarQube_Publish, Deploy_To_UAT]
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0
    steps:
      - uses: actions/checkout@v1

      - name: Run Validation against Production
        run: sfdx deploy:source --sourcepath force-app/main/default --checkonly --testlevel NoTestRun --targetalias PROD
