name: SIT Branch Workflow

on:
  push:
    branches: [SIT]
    paths:
      - "force-app/**"

env:
  TOKEN: ${{ secrets.TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  SF_ORG__SIT__AUTH_URL: ${{ secrets.SF_ORG__SIT__AUTH_URL }}

jobs:
  Merge_to_SIT:
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0
    steps:
      - uses: actions/checkout@v1

      - name: Populate auth file with SFDX_URL secret
        shell: bash
        run: echo ${{ secrets.SF_ORG__SIT__AUTH_URL}} > ./SFDX_URL_STORE.txt

      - name: Authenticate against dev hub
        run : sfdx force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=DevHub --setdefaultdevhubusername

      - name: Deployment against SIT
        run: sfdx force:source:deploy --sourcepath Diff_Folder --testlevel NoTestRun --targetusername DevHub

      - name: Update deploy status
        if: always()
        run: |
          status: ${{ job.status }}
          echo
