# This is a basic workflow to help you get started with Actions

name: Run on push of tags

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy_To_PROD:
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0

    steps:
      - uses: actions/checkout@v1

      - name: Run Deployment against UAT
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          SF_ORG__PROD__AUTH_URL: ${{ secrets.SF_ORG__PROD__AUTH_URL }}
        run: sfdx deploy:source --sourcepath force-app/main/default --testlevel NoTestRun --targetalias PROD
